version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  db:
    image: "postgres"
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
