version: '3.1'

services:
  app:
    image: "sha256:8e11977a7b2623284b44792ef0e1fbd35aa17752bbd603b8b039903488482836"
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  db:
    image: "postgres"
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin